/**
 * Textes d'interface. Choix de l'auteur : interface en ANGLAIS, mots très courts, identique dans
 * les trois langues (UI) ; les messages d'erreur, les mentions et les libellés lus par les lecteurs
 * d'écran restent traduits FR / JA / EN. {x} = valeur insérée.
 */
const UI = {
  drop: 'Drop', send: 'Drop', sending: '…', processing: '…',
  empty: 'No posts yet.', startWall: 'Start the wall.',
  context: 'A moderated wall for images and words.',
  thisMonth: 'This month: {prompt}',
  // manifeste (panneau Mood)
  m1: 'Images and words, left by anyone.', m2: 'Nothing appears before review.',
  m3: 'Time slowly fades the wall.', m4: 'Old traces sink into the list.',
  prev: 'Previous', next: 'Next',
  pending: 'Under review',
  report: 'Report', reportSend: 'Send', reportThanks: 'Thanks',
  rRights: 'Rights', rOffensive: 'Offensive', rPersonal: 'Private', rSpam: 'Spam', rOther: 'Other',
  anon: 'Anon',
  chooseImage: 'Image', changeImage: 'Change', removeImage: 'Remove',
  imageHint: 'JPEG · PNG · WebP · 5 MB',
  processed: '{w} × {h}',
  size: 'Size',
  textPlaceholder: 'Leave a trace…', nameLabel: 'Name', count: '{n} / {max}',
  rights: 'I have the rights',
  thanks: 'Sent. Under review.', thanksMock: 'Mock — nothing sent',
  viewWall: 'Wall', viewList: 'List',
  captchaMock: 'Not a robot (mock)',
};

export const STRINGS = {
  fr: {
    ...UI,
    // lus par les lecteurs d'écran (invisibles) et mentions : traduits
    siteMenu: 'Mood — à propos',
    skip: 'Aller au contenu',
    close: 'Fermer',
    imageBy: 'Image déposée par {name}',
    textBy: 'Texte déposé par {name}',
    reportTitle: 'Signaler ce contenu',
    mentions: 'Les dépôts sont modérés : rien n’est publié sans validation. En déposant, vous confirmez détenir les droits sur ce que vous publiez. Pour demander un retrait : {email}.',
    // erreurs : traduites, courtes
    eTooBig: 'Trop lourd · 5 Mo max',
    eTooBigSrv: 'Trop lourd · 5 Mo max',
    eType: 'Format refusé',
    eDecode: 'Image illisible',
    eMeta: 'Métadonnées non retirées',
    eEmpty: 'Image ou mots',
    eTooLong: '{max} max',
    eRights: 'Cochez les droits',
    eCaptcha: 'Vérification',
    eRate: 'Trop de dépôts',
    eName: 'Pas de lien',
    eGone: 'Retiré',
    eNetwork: 'Hors ligne',
    eServer: 'Erreur',
  },
  ja: {
    ...UI,
    // lus par les lecteurs d'écran (invisibles) et mentions : traduits
    siteMenu: 'Mood — このサイトについて',
    skip: 'コンテンツへ移動',
    close: '閉じる',
    imageBy: '{name}さんが投稿した画像',
    textBy: '{name}さんが投稿したテキスト',
    reportTitle: 'この投稿を報告',
    mentions: '投稿はすべて確認後に掲載されます。投稿することで、その内容の権利を持っていることを確認したものとみなします。削除のご依頼：{email}',
    // erreurs : traduites, courtes
    eTooBig: '重すぎます · 5MBまで',
    eTooBigSrv: '重すぎます · 5MBまで',
    eType: '非対応の形式',
    eDecode: '読み込めません',
    eMeta: 'メタデータを削除できません',
    eEmpty: '画像か言葉を',
    eTooLong: '{max} max',
    eRights: '権利にチェック',
    eCaptcha: '認証してください',
    eRate: '投稿が多すぎます',
    eName: 'リンク不可',
    eGone: '削除済み',
    eNetwork: 'オフライン',
    eServer: 'エラー',
  },
  en: {
    ...UI,
    // lus par les lecteurs d'écran (invisibles) et mentions : traduits
    siteMenu: 'Mood — about',
    skip: 'Skip to content',
    close: 'Close',
    imageBy: 'Image shared by {name}',
    textBy: 'Text shared by {name}',
    reportTitle: 'Report this post',
    mentions: 'Posts are moderated: nothing is published without approval. By posting, you confirm you own the rights to what you share. To request removal: {email}.',
    // erreurs : traduites, courtes
    eTooBig: 'Too heavy · 5 MB max',
    eTooBigSrv: 'Too heavy · 5 MB max',
    eType: 'JPEG, PNG, WebP only',
    eDecode: 'Unreadable image',
    eMeta: 'Metadata not removed',
    eEmpty: 'Add an image or words',
    eTooLong: '{max} max',
    eRights: 'Tick the rights box',
    eCaptcha: 'Complete the check',
    eRate: 'Too many — later',
    eName: 'No links in name',
    eGone: 'Gone',
    eNetwork: 'Offline',
    eServer: 'Error — retry',
  },
};
