/**
 * Textes d'interface. Choix de l'auteur : interface en ANGLAIS, mots très courts, identique dans
 * les trois langues (UI) ; les messages d'erreur, les mentions et les libellés lus par les lecteurs
 * d'écran restent traduits FR / JA / EN. {x} = valeur insérée.
 */
const UI = {
  drop: 'Drop', send: 'Drop', sending: '…', processing: '…',
  more: 'More', empty: 'Empty',
  report: 'Report', reportSend: 'Send', reportThanks: 'Thanks',
  rRights: 'Rights', rOffensive: 'Offensive', rPersonal: 'Private', rSpam: 'Spam', rOther: 'Other',
  anon: 'Anon',
  chooseImage: 'Image', changeImage: 'Change', removeImage: 'Remove',
  imageHint: 'JPEG · PNG · WebP · 5 MB — MP4 · MOV · 10 s',
  start: 'Start',
  processed: '{w} × {h}',
  size: 'Size', grain: 'Grain',
  textPlaceholder: 'Words', nameLabel: 'Name', count: '{n} / {max}',
  rights: 'I own the rights',
  thanks: 'Sent — pending review', thanksMock: 'Mock — nothing sent',
  viewWall: 'Wall', viewList: 'List',
  stampLegend: '= author',
  captchaMock: 'Not a robot (mock)',
  tilt: 'Tilt',
};

export const STRINGS = {
  fr: {
    ...UI,
    // lus par les lecteurs d'écran (invisibles) et mentions : traduits
    siteMenu: 'Mood — à propos',
    skip: 'Aller au contenu',
    close: 'Fermer',
    byAuthor: 'Dépôt de l’auteur du site',
    imageBy: 'Image déposée par {name}',
    textBy: 'Texte déposé par {name}',
    reportTitle: 'Signaler ce contenu',
    mentions: 'Les dépôts sont modérés : rien n’est publié sans validation. En déposant, vous confirmez détenir les droits sur ce que vous publiez. Pour demander un retrait : {email}.',
    videoBy: 'Vidéo déposée par {name}',
    // erreurs : traduites, courtes
    eTooBig: 'Trop lourd · 5 Mo max',
    eTooBigSrv: 'Trop lourd · 5 Mo max',
    eType: 'Format refusé',
    eDecode: 'Image illisible',
    eMeta: 'Métadonnées non retirées',
    eEmpty: 'Image ou mots',
    eTooLong: '{max} max',
    eRights: 'Cochez les droits',
    eCaptcha: 'Vérification',
    eRate: 'Trop de dépôts',
    eName: 'Pas de lien',
    eGone: 'Retiré',
    eNetwork: 'Hors ligne',
    eServer: 'Erreur',
    eVideoUnsupported: 'Vidéo impossible sur ce navigateur',
    eVideoDecode: 'Vidéo illisible',
    eVideoTooBig: 'Vidéo trop lourde',
    eVideo: 'Vidéo refusée',
    eFull: 'Plus de place pour les vidéos',
  },
  ja: {
    ...UI,
    // lus par les lecteurs d'écran (invisibles) et mentions : traduits
    siteMenu: 'Mood — このサイトについて',
    skip: 'コンテンツへ移動',
    close: '閉じる',
    byAuthor: 'サイト運営者の投稿',
    imageBy: '{name}さんが投稿した画像',
    textBy: '{name}さんが投稿したテキスト',
    reportTitle: 'この投稿を報告',
    mentions: '投稿はすべて確認後に掲載されます。投稿することで、その内容の権利を持っていることを確認したものとみなします。削除のご依頼：{email}',
    videoBy: '{name}さんが投稿した動画',
    // erreurs : traduites, courtes
    eTooBig: '重すぎます · 5MBまで',
    eTooBigSrv: '重すぎます · 5MBまで',
    eType: '非対応の形式',
    eDecode: '読み込めません',
    eMeta: 'メタデータを削除できません',
    eEmpty: '画像か言葉を',
    eTooLong: '{max} max',
    eRights: '権利にチェック',
    eCaptcha: '認証してください',
    eRate: '投稿が多すぎます',
    eName: 'リンク不可',
    eGone: '削除済み',
    eNetwork: 'オフライン',
    eServer: 'エラー',
    eVideoUnsupported: 'このブラウザでは動画を扱えません',
    eVideoDecode: '動画を読み込めません',
    eVideoTooBig: '動画が重すぎます',
    eVideo: '動画は受け付けられません',
    eFull: '動画の保存容量がいっぱいです',
  },
  en: {
    ...UI,
    // lus par les lecteurs d'écran (invisibles) et mentions : traduits
    siteMenu: 'Mood — about',
    skip: 'Skip to content',
    close: 'Close',
    byAuthor: 'Posted by the site author',
    imageBy: 'Image shared by {name}',
    textBy: 'Text shared by {name}',
    reportTitle: 'Report this post',
    mentions: 'Posts are moderated: nothing is published without approval. By posting, you confirm you own the rights to what you share. To request removal: {email}.',
    videoBy: 'Video shared by {name}',
    // erreurs : traduites, courtes
    eTooBig: 'Too heavy · 5 MB max',
    eTooBigSrv: 'Too heavy · 5 MB max',
    eType: 'JPEG, PNG, WebP only',
    eDecode: 'Unreadable image',
    eMeta: 'Metadata not removed',
    eEmpty: 'Add an image or words',
    eTooLong: '{max} max',
    eRights: 'Tick the rights box',
    eCaptcha: 'Complete the check',
    eRate: 'Too many — later',
    eName: 'No links in name',
    eGone: 'Gone',
    eNetwork: 'Offline',
    eServer: 'Error — retry',
    eVideoUnsupported: 'Video not possible in this browser',
    eVideoDecode: 'Unreadable video',
    eVideoTooBig: 'Video too heavy',
    eVideo: 'Video refused',
    eFull: 'No more room for videos',
  },
};
