/** Textes d'interface FR / JA / EN. {x} = valeur insérée. */
export const STRINGS = {
  fr: {
    siteMenu: 'Mood — à propos',
    moderated: 'Dépôts modérés.',
    skip: 'Aller au contenu',
    viewLabel: 'Affichage', viewWall: 'Mur', viewList: 'Liste',
    about: 'À propos', contact: 'Contact', drop: 'Déposer', close: 'Fermer',
    more: 'Voir plus anciens', empty: 'Le mur est encore vide.',
    mockBanner: 'Maquette',
    byAuthor: 'Dépôt de l’auteur du site', anon: 'Anonyme', imageBy: 'Image déposée par {name}', textBy: 'Texte déposé par {name}',
    report: 'Signaler', reportTitle: 'Signaler ce contenu',
    rRights: 'Atteinte à mes droits (je suis l’auteur)', rOffensive: 'Contenu choquant ou haineux',
    rPersonal: 'Données personnelles', rSpam: 'Spam ou publicité', rOther: 'Autre',
    reportSend: 'Envoyer le signalement', reportThanks: 'Merci. Le contenu sera examiné rapidement.',
    dropTitle: 'Déposer sur le mur', tabImage: 'Image', tabText: 'Texte',
    chooseImage: 'Choisir une image', changeImage: 'Changer d’image',
    imageHint: 'JPEG, PNG ou WebP · 5 Mo max. Plus l’image a de pixels, moins il reste de place pour les mots.',
    processing: 'Préparation de l’image…',
    processed: '{w} × {h} px · {size} · métadonnées retirées',
    textLabel: 'Votre texte', count: '{n} / {max}',
    nameLabel: 'Pseudo (facultatif)',
    rights: 'J’ai les droits sur ce contenu. Il sera publié après validation.',
    captchaMock: 'Je ne suis pas un robot (simulé)',
    send: 'Envoyer', sending: 'Envoi…',
    thanks: 'Merci ! Votre dépôt sera visible après validation.',
    thanksMock: 'Maquette : rien n’a été envoyé. Dans le vrai site, votre dépôt serait visible après validation.',
    eTooBig: 'Fichier trop lourd ({size}). Maximum : 5 Mo.',
    eType: 'Format non accepté. Utilisez JPEG, PNG ou WebP.',
    eDecode: 'Impossible de lire cette image.',
    eMeta: 'Les métadonnées n’ont pas pu être retirées : envoi bloqué.',
    eNoImage: 'Choisissez une image.', eNoText: 'Écrivez un texte (500 caractères maximum).',
    eRights: 'Cochez la case sur les droits.', eCaptcha: 'Validez la vérification anti-robot.',
    mentions: 'Les dépôts sont modérés : rien n’est publié sans validation. En déposant, vous confirmez détenir les droits sur ce que vous publiez. Pour demander un retrait : {email}.',
    stampLegend: 'Le petit carré clair signale les dépôts de l’auteur du site.',
    textPlaceholder: 'Des mots (facultatifs avec une image)',
    removeImage: 'Retirer l’image',
    budgetNone: 'Sans image : {max} caractères',
    budgetImage: 'Cette image laisse {max} caractères',
    eEmpty: 'Ajoutez une image, des mots, ou les deux.',
    eTooLong: 'Trop long : {max} caractères au maximum avec cette image.',
    eRate: 'Trop de dépôts depuis cette connexion. Réessayez plus tard.',
    eName: 'Pseudo refusé : pas de lien ni d’adresse.',
    eGone: 'Ce contenu n’est plus en ligne.',
    eNetwork: 'Connexion impossible. Vérifiez le réseau et réessayez.',
    eServer: 'Une erreur est survenue. Réessayez dans un instant.',
    eTooBigSrv: 'Fichier trop lourd. Maximum : 5 Mo.',
  },
  ja: {
    siteMenu: 'Mood — このサイトについて',
    moderated: '投稿は承認制です。',
    skip: 'コンテンツへ移動',
    viewLabel: '表示', viewWall: 'ウォール', viewList: 'リスト',
    about: 'プロフィール', contact: '連絡先', drop: '投稿する', close: '閉じる',
    more: '以前の投稿を見る', empty: 'まだ投稿がありません。',
    mockBanner: 'モックアップ',
    byAuthor: 'サイト運営者の投稿', anon: '匿名', imageBy: '{name}さんが投稿した画像', textBy: '{name}さんが投稿したテキスト',
    report: '報告', reportTitle: 'この投稿を報告',
    rRights: '自分の権利の侵害（私が作者です）', rOffensive: '不快・差別的な内容',
    rPersonal: '個人情報', rSpam: 'スパム・広告', rOther: 'その他',
    reportSend: '報告を送信', reportThanks: 'ありがとうございます。速やかに確認します。',
    dropTitle: 'ウォールに投稿', tabImage: '画像', tabText: 'テキスト',
    chooseImage: '画像を選ぶ', changeImage: '画像を変更',
    imageHint: 'JPEG・PNG・WebP、5MBまで。画像の画素数が多いほど、書ける文字数は少なくなります。',
    processing: '画像を準備しています…',
    processed: '{w} × {h} px · {size} · メタデータ削除済み',
    textLabel: 'テキスト', count: '{n} / {max}',
    nameLabel: 'ニックネーム（任意）',
    rights: 'この内容の権利を持っています。承認後に掲載されます。',
    captchaMock: 'ロボットではありません（疑似）',
    send: '送信', sending: '送信中…',
    thanks: 'ありがとうございます！承認後に掲載されます。',
    thanksMock: 'モックアップのため送信されていません。実際のサイトでは、承認後に掲載されます。',
    eTooBig: 'ファイルが大きすぎます（{size}）。上限は5MBです。',
    eType: '対応していない形式です。JPEG・PNG・WebPをお使いください。',
    eDecode: 'この画像を読み込めません。',
    eMeta: 'メタデータを削除できなかったため、送信を中止しました。',
    eNoImage: '画像を選んでください。', eNoText: 'テキストを入力してください（500文字まで）。',
    eRights: '権利についてのチェックを入れてください。', eCaptcha: 'ボット対策の確認を完了してください。',
    mentions: '投稿はすべて確認後に掲載されます。投稿することで、その内容の権利を持っていることを確認したものとみなします。削除のご依頼：{email}',
    stampLegend: '小さな白い四角は、サイト運営者の投稿の印です。',
    textPlaceholder: 'ことば（画像がある場合は任意）',
    removeImage: '画像を外す',
    budgetNone: '画像なし：{max}文字まで',
    budgetImage: 'この画像なら{max}文字まで',
    eEmpty: '画像かことば、またはその両方を入れてください。',
    eTooLong: '長すぎます。この画像では{max}文字までです。',
    eRate: 'この接続からの投稿が多すぎます。しばらくしてから再度お試しください。',
    eName: 'このニックネームは使えません（リンクやアドレスは不可）。',
    eGone: 'この投稿はすでに公開されていません。',
    eNetwork: '接続できません。通信環境を確認して、もう一度お試しください。',
    eServer: 'エラーが発生しました。少し待ってから再度お試しください。',
    eTooBigSrv: 'ファイルが大きすぎます。上限は5MBです。',
  },
  en: {
    siteMenu: 'Mood — about',
    moderated: 'Posts are moderated.',
    skip: 'Skip to content',
    viewLabel: 'View', viewWall: 'Wall', viewList: 'List',
    about: 'About', contact: 'Contact', drop: 'Contribute', close: 'Close',
    more: 'Show older', empty: 'The wall is still empty.',
    mockBanner: 'Mockup',
    byAuthor: 'Posted by the site author', anon: 'Anonymous', imageBy: 'Image shared by {name}', textBy: 'Text shared by {name}',
    report: 'Report', reportTitle: 'Report this post',
    rRights: 'Infringes my rights (I am the author)', rOffensive: 'Offensive or hateful',
    rPersonal: 'Personal data', rSpam: 'Spam or advertising', rOther: 'Other',
    reportSend: 'Send report', reportThanks: 'Thank you. This post will be reviewed shortly.',
    dropTitle: 'Add to the wall', tabImage: 'Image', tabText: 'Text',
    chooseImage: 'Choose an image', changeImage: 'Change image',
    imageHint: 'JPEG, PNG or WebP · 5 MB max. The more pixels the image has, the fewer words you can add.',
    processing: 'Preparing the image…',
    processed: '{w} × {h} px · {size} · metadata removed',
    textLabel: 'Your text', count: '{n} / {max}',
    nameLabel: 'Name or nickname (optional)',
    rights: 'I own the rights to this content. It will appear once approved.',
    captchaMock: 'I am not a robot (simulated)',
    send: 'Send', sending: 'Sending…',
    thanks: 'Thank you! Your post will appear once approved.',
    thanksMock: 'Mockup: nothing was sent. On the real site, your post would appear once approved.',
    eTooBig: 'File too large ({size}). Maximum: 5 MB.',
    eType: 'Unsupported format. Please use JPEG, PNG or WebP.',
    eDecode: 'This image could not be read.',
    eMeta: 'Metadata could not be removed: upload blocked.',
    eNoImage: 'Please choose an image.', eNoText: 'Please write a text (500 characters max).',
    eRights: 'Please tick the rights box.', eCaptcha: 'Please complete the anti-bot check.',
    mentions: 'Posts are moderated: nothing is published without approval. By posting, you confirm you own the rights to what you share. To request removal: {email}.',
    stampLegend: 'The small light square marks posts by the site author.',
    textPlaceholder: 'Words (optional with an image)',
    removeImage: 'Remove image',
    budgetNone: 'No image: {max} characters',
    budgetImage: 'This image leaves {max} characters',
    eEmpty: 'Add an image, some words, or both.',
    eTooLong: 'Too long: {max} characters max with this image.',
    eRate: 'Too many posts from this connection. Please try again later.',
    eName: 'Name refused: no links or addresses.',
    eGone: 'This post is no longer online.',
    eNetwork: 'Cannot connect. Check your network and try again.',
    eServer: 'Something went wrong. Please try again in a moment.',
    eTooBigSrv: 'File too large. Maximum: 5 MB.',
  },
};
