/** Textes d'interface, trilingues. Les clés sont utilisées via data-i18n="…" ou t('…'). */
export const STRINGS = {
  fr: {
    skipToIndex: 'Index', index: 'Index', about: 'À propos', pause: 'Pause', close: 'Fermer',
    openSheet: 'Fiche', enterSpace: 'Entrer dans l’espace', seeInSpace: 'Voir dans l’espace',
    identLine: 'Image, montage, direction artistique — Tokyo / Paris',
    loading: 'Chargement de l’espace…', loadingModel: 'Coulage du béton…', loadingLight: 'Lumière précalculée…',
    ready: 'Prêt', noGL: 'Affichage 3D indisponible sur cet appareil : voici l’index.',
    lowPower: 'Mode économie de données : l’index s’affiche d’abord.',
    colTitle: 'Titre', colFormat: 'Format', colDuration: 'Durée',
    works: n => `${n} œuvres`, unknownDuration: 'durée à renseigner',
    indexFoot: 'Longueur des traits : durée des films (échelle en racine carrée pour que les formats courts restent visibles). Survoler ou glisser sur une vignette pour la parcourir image par image.',
    watch: 'Voir le film', path: 'Parcours', contact: 'Contact', format: 'Format', duration: 'Durée', year: 'Année',
    intro: 'Entrée', via: 'Passage', placeholderNote: 'Emplacement réservé',
    stationOf: (i, n) => `Plan ${i}/${n}`,
    lockTitle: 'Cliquer pour entrer',
    lockHow: 'Souris : regarder · ZQSD ou flèches : marcher · Maj : courir · Espace : sauter · Clic sur une œuvre : fiche · Échap : libérer la souris · I : index',
    touchHow: 'Joystick : marcher (à fond pour courir) · Glisser : regarder · Toucher une œuvre : fiche',
    aimHint: 'Clic ou E : ouvrir la fiche',
  },
  ja: {
    skipToIndex: 'インデックス', index: 'インデックス', about: 'プロフィール', pause: '一時停止', close: '閉じる',
    openSheet: '詳細', enterSpace: '空間に入る', seeInSpace: '空間で見る',
    identLine: '映像・編集・アートディレクション — 東京 / パリ',
    loading: '空間を読み込み中…', loadingModel: 'コンクリートを打設中…', loadingLight: 'ライトマップを読み込み中…',
    ready: '準備完了', noGL: 'この端末では3D表示ができないため、インデックスを表示しています。',
    lowPower: 'データセーバーが有効なため、先にインデックスを表示します。',
    colTitle: 'タイトル', colFormat: 'フォーマット', colDuration: '尺',
    works: n => `${n}作品`, unknownDuration: '尺未入力',
    indexFoot: '線の長さは作品の尺を表します（短い作品も見えるよう平方根スケール）。サムネイルにカーソルを重ねる、またはスワイプするとコマ送りで確認できます。',
    watch: '映像を見る', path: '経歴', contact: '連絡先', format: 'フォーマット', duration: '尺', year: '年',
    intro: 'エントランス', via: '通路', placeholderNote: '予約スロット',
    stationOf: (i, n) => `カット ${i}/${n}`,
    lockTitle: 'クリックして入る',
    lockHow: 'マウス：見回す・WASD／矢印キー：歩く・Shift：走る・スペース：ジャンプ・作品をクリック：詳細・Esc：マウスを解放・I：インデックス',
    touchHow: 'スティック：歩く（大きく倒すと走る）・ドラッグ：見回す・作品をタップ：詳細',
    aimHint: 'クリックまたはE：詳細を開く',
  },
  en: {
    skipToIndex: 'Index', index: 'Index', about: 'About', pause: 'Pause', close: 'Close',
    openSheet: 'Details', enterSpace: 'Enter the space', seeInSpace: 'See in the space',
    identLine: 'Image, editing, art direction — Tokyo / Paris',
    loading: 'Loading the space…', loadingModel: 'Pouring the concrete…', loadingLight: 'Baked light…',
    ready: 'Ready', noGL: '3D is not available on this device: here is the index.',
    lowPower: 'Data saver is on: showing the index first.',
    colTitle: 'Title', colFormat: 'Format', colDuration: 'Length',
    works: n => `${n} works`, unknownDuration: 'length to be added',
    indexFoot: 'Line length: running time (square-root scale so short pieces stay visible). Hover or drag across a thumbnail to step through it frame by frame.',
    watch: 'Watch the film', path: 'Background', contact: 'Contact', format: 'Format', duration: 'Length', year: 'Year',
    intro: 'Entrance', via: 'Passage', placeholderNote: 'Reserved slot',
    stationOf: (i, n) => `Shot ${i}/${n}`,
    lockTitle: 'Click to enter',
    lockHow: 'Mouse: look · WASD or arrows: walk · Shift: run · Space: jump · Click a work: details · Esc: release the mouse · I: index',
    touchHow: 'Joystick: walk (push fully to run) · Drag: look · Tap a work: details',
    aimHint: 'Click or E: open details',
  },
};
